#!/usr/bin/env python
# coding: utf-8

# # DS/CMPSC 410 MiniProject Deliverable #3
# 
# # Fall 2024
# ### Instructor: Prof. John Yen
# ### TA: Jin, Peng and Al Lawati, Ali Hussain Mohsin
# 
# ### Learning Objectives
# - Be able to apply PCA to reduce the high dimensional feature space to facilitate ML for high dimensional data.
# - Like Minproject Deliverable #2, focus on the clustering of non-extreme multi-port scanners based on the 100 top ports they scanned.
# - Be able to reduce the high dimensionality of One-Hot-Encoded features using Principal Component Analysis (PCA)
# - Be able to perform k-means with and without dimension reduction using PCA, and compare the results using silhouette score and mirai external labels.
# - Be able to obtain cluster centers of the original feature space for clustering results using PCA and k-means.
# - After successful clustering of the small Darknet dataset (with and without dimension reduction using PCA), conduct clustering on the large Darknet dataset in the cluster mode.
# - Compare the clustering results of the large dataset with and without dimension reduction using PCA.
# 
# ## Submit the following items:
# - Successfully completed Jupyter Notebook (run in local mode), in html format.
# - Items for cluster mode (Exercise 8):
# - - Submit the .py file  (5 points)
# - - Submit the the log file that contains the run time information for a successful execution in the cluster mode. (5 points)
# - - Submit the output file that records the cluster summary in the cluster mode (without PCA) (10 points)
# - - Submit the output file that records the cluster summary in the cluster mode (with PCA) (10 points)
# - - Discuss the Silihouette score and Mirai ratio of clusters generated by k-means clustering with PCA and without PCA (in a separate word document) (10 points)
# 
# ### Total points: 100 
# - Exercise 1: 5 points
# - Exercise 2: 5 points 
# - Exercise 3: 5 points 
# - Exercise 4: 5 points
# - Exercise 5: 5 points
# - Exercise 6: 10 points
# - Exercise 7: 25 points
# - Exercise 8: 40 points
#   
# ### Due: 11:59 pm, December 2, 2024
# ### Early Submission bonus (before midnight November 22nd): 10 points

# In[1]:


import pyspark
import csv


# In[2]:


from pyspark import SparkContext
from pyspark.sql import SparkSession
from pyspark.sql.types import StructField, StructType, StringType, LongType
from pyspark.sql.functions import col, column
from pyspark.sql.functions import expr
from pyspark.sql.functions import split
from pyspark.sql.functions import array_contains
from pyspark.sql import Row
from pyspark.ml import Pipeline
from pyspark.ml.feature import OneHotEncoder, StringIndexer, VectorAssembler, IndexToString
from pyspark.ml.clustering import KMeans
from pyspark.ml.evaluation import ClusteringEvaluator
from pyspark.ml.feature import PCA


# In[3]:


ss = SparkSession.builder.appName("MiniProject 3 PCA for k-meas Clustering using OHE").getOrCreate()


# ss.sparkContext.setLogLevel("WARN")

# # We can use the header of data files to infer schema.

# ## Exercise 1 (5 points)
# Complete the path for input file in the code below and enter your name in this Markdown cell:
# - Name: Tyler Korz
# ### Note: You will need to change the name of the input file in the cluster mode to `Day_2020_profile.csv`

# In[4]:


Scanners_df = ss.read.csv("/storage/home/tkk5297/work/MiniProj3/Day_2020_profile.csv", header= True, inferSchema=True )


# ## We can use printSchema() to display the schema of the DataFrame Scanners_df to see whether it was inferred correctly.

# In[5]:


Scanners_df.printSchema()


# # In this lab, our goal is to implement and evaluate the results for reducing the dimensionality of feature space using PCA.
# 
# ## Like MiniProject 2, we can filter out those scanners that scan only 1 port, because they can be easily grouped using groupBy on ``ports_scanned_str``

# ### Because the feature `numports` record the total number of ports being scanned by each scanner, we can use it to separate 1-port-scanners from multi-port-scanners.

# In[6]:


multi_port_scanners= Scanners_df.where(col("numports")>1)


# In[7]:


multi_port_scanners_count = multi_port_scanners.count()


# In[8]:


print(multi_port_scanners_count)


# # Like Miniproject 2, we select a threashold for extreme scanners based on the largest number of ports that are scanned by at least two scanners

# In[9]:


ScannersCount_byNumPorts = multi_port_scanners.groupby("numports").count()


# In[10]:


ScannersCount_byNumPorts.show(3)


# # Exercise 2 (5 points)
# Complete the code below to (1) sort the DataFrame ScannersCount_byNumPorts in descending order, and (2) filter out ``numports`` that are associated with only one scanner.

# In[11]:


SortedScannersCount_byNumPorts= ScannersCount_byNumPorts.orderBy(col("numports"), ascending=False)


# In[12]:


non_rare_NumPorts = SortedScannersCount_byNumPorts.where(col("numports") > 1)


# In[13]:


non_rare_NumPorts.show(5)


# # Like MiniProject 2, we use DataFrame aggregation method ``agg({ "numports" : "max" })`` to find the  the maximum of numports column.
# ## The result is a DataFrame with only column named as ``max(numports)``

# In[14]:


max_non_rare_NumPorts_df = non_rare_NumPorts.agg({"numports" : "max"})
max_non_rare_NumPorts_df.show()


# In[15]:


max_non_rare_NumPorts_rdd = max_non_rare_NumPorts_df.rdd.map(lambda x: x[0])
max_non_rare_NumPorts_rdd.take(1)


# In[16]:


max_non_rare_NumPorts_list = max_non_rare_NumPorts_rdd.collect()
print(max_non_rare_NumPorts_list)


# In[17]:


max_non_rare_NumPorts=max_non_rare_NumPorts_list[0]
print(max_non_rare_NumPorts)


# ## Like Miniproject 2, we are going to focus on the grouping of scanners that scan at least two ports, and do not scan very large number of ports (i.e., Non-extreme Multi-port Scanners). We will save the extreme scanners in a csv file so that we can process it separately.
# ## Like Miniproject 2, we will use ``local`` directory to store output files in the local mode, use ``cluster`` directory to store output files in the cluster mode.

# In[18]:


extreme_scanners = Scanners_df.where(col("numports") > max_non_rare_NumPorts)


# In[19]:


path2="/storage/home/tkk5297/work/MiniProj3/cluster/Extreme_Scanners.csv"
extreme_scanners.write.option("header",True).csv(path2)


# In[20]:


non_extreme_multi_port_scanners = Scanners_df.where(col("numports") <= max_non_rare_NumPorts).where(col("numports") > 1)


# In[21]:


non_extreme_multi_port_scanners.count()


# # Part A: One Hot Encoding of Top 100 Ports
# - Like Miniproject 2, we want to apply one hot encoding to the top 100 ports scanned by scanners.  
# - Unlike Miniproject 2, however, we will apply PCA to reduce the dimensionality (from 100 port features to 30 PCA features )

# In[22]:


non_extreme_multi_port_scanners.select("ports_scanned_str").show(4)


# # For each port scanned, count the Total Number of Scanners that Scan the Given Port
# Like MiniProject 2, to calculate this, we need to 
# - (a) convert the ports_scanned_str into an array/list of ports
# - (b) Convert the DataFrame into an RDD
# - (c) Use flatMap to count the total number of scanners for each port.

# ## (a) Split the column "Ports_Array" into an Array of ports.

# In[23]:


# (a)
NEMP_Scanners_df=non_extreme_multi_port_scanners.withColumn("Ports_Array", split(col("ports_scanned_str"), "-") )
NEMP_Scanners_df.show(2)


# ## (b) We convert the column ```Ports_Array``` into an RDD so that we can apply flatMap for counting.

# In[24]:


Ports_Scanned_RDD = NEMP_Scanners_df.select("Ports_Array").rdd


# In[25]:


Ports_Scanned_RDD.take(2)


# ## (c) Like Miniproject 2, we can count the total number of scanners for each port by counting the total occurance of each port number through flatMap.
# ### We can then count the total number of occurance of a port using map and reduceByKey, like counting word/hashtag frequency in tweets.

# In[26]:


Ports_Scanned_RDD.take(3)


# In[27]:


Ports_list_RDD = Ports_Scanned_RDD.flatMap(lambda row: row.Ports_Array )


# In[28]:


Ports_list_RDD.take(3)


# In[29]:


Port_1_RDD = Ports_list_RDD.map(lambda x: (x, 1))
Port_1_RDD.take(2)


# In[30]:


Port_count_RDD = Port_1_RDD.reduceByKey(lambda x,y: x+y, 5)
Port_count_RDD.take(3)


# In[31]:


Port_count_RDD.count()


# ## Exercise 3 (5 points) Complete the code below to finds top 100 ports scanned by non-extreme multi-port scanners. We use top 100 ports for Mini-project 3 (both local mode and cluster mode).

# In[32]:


Sorted_Count_Port_RDD = Port_count_RDD.map(lambda x: (x[1], x[0])).sortByKey( ascending = False)


# In[33]:


top_k_ports = 100


# In[34]:


Sorted_Ports_RDD= Sorted_Count_Port_RDD.map(lambda x: x[1] )
Top_Ports_list = Sorted_Ports_RDD.take(top_k_ports)


# In[35]:


Top_Ports_list


# #  A.2 One Hot Encoding of Top K Ports
# ## One-Hot-Encoded Feature/Column Name
# Like Mini Project 2, we need to create a name for each one-hot-encoded feature. We adopt the convention that the column name for each top k port is "PortXXXX", where "XXXX" is a port number. This can be done by concatenating "Port" with a port number (string) in the sorted list ``Top_Ports_list`` using ``+``.

# In[36]:


Top_Ports_list[99]


# In[37]:


FeatureName = "Port"+Top_Ports_list[99]


# In[38]:


FeatureName


# ## One-Hot-Encoding using withColumn and array_contains

# In[39]:


from pyspark.sql.functions import array_contains


# ## Similar to MiniProject 2, generate Hot-One Encoded Feature for each of the top k ports in the Top_Ports_list
# 
# - Iterate through the Top_Ports_list so that each top port is one-hot encoded into the DataFrame for non-extreme multi-port scanners (i.e., `NEMP_Scanners2.df`).

# ## Exercise 4 (5 points) Complete the following PySpark code for encoding the n ports using One Hot Encoding, where n is specified by the variable ```top_k_ports```

# In[40]:


top_k_ports


# In[41]:


Top_Ports_list[top_k_ports - 1]


# In[42]:


# Initialize NEMP_Scanners2_df
NEMP_Scanners2_df = NEMP_Scanners_df
for i in range(0, top_k_ports):
    # "Port" + Top_Ports_list[i]  is the name of each new feature created through One Hot Encoding Top_Ports_list
    NEMP_Scanners3_df = NEMP_Scanners2_df.withColumn("Port" + Top_Ports_list[i], array_contains("Ports_Array", Top_Ports_list[i]))
    NEMP_Scanners2_df = NEMP_Scanners3_df


# In[43]:


# Initialize NEMP_Scanners2_df
NEMP_Scanners2_df = NEMP_Scanners_df
NEMP_Scanners_df.persist()


# In[50]:


NEMP_Scanners2_df.printSchema()


# ## Exercise 5 (5 points)  Complete the code below to use k-means to cluster non-extreme multi-port scanners using one-hot-encoded top 200 ports.

# # Specify One-Hot Encoded Top k Ports as Input Features for k Means Clustering

# In[51]:


input_features = [ ]
for i in range(0, top_k_ports ):
    input_features.append("Port"+ Top_Ports_list[i])


# In[52]:


print(input_features)


# # Part B k-Means Clustering (number of clusters k=200)

# In[56]:


va = VectorAssembler().setInputCols(input_features).setOutputCol("features")


# In[57]:


NEMP_Scanners2_df.printSchema()


# In[60]:


data= va.transform(NEMP_Scanners3_df)


# In[61]:


data.show(3)


# In[62]:


data.persist()


# In[63]:


total_clusters = 200
km = KMeans(featuresCol= "features", predictionCol="prediction").setK(total_clusters).setSeed(123)
km.explainParams()


# In[64]:


kmModel=km.fit(data)


# In[65]:


NEMP_Scanners_df.unpersist()


# In[66]:


kmModel


# In[67]:


predictions = kmModel.transform(data)


# In[68]:


predictions.persist()


# In[69]:


predictions.show(1)


# In[70]:


Cluster1_df=predictions.where(col("prediction")==0)


# In[71]:


Cluster1_df.count()


# In[72]:


summary = kmModel.summary


# In[73]:


summary.clusterSizes


# In[74]:


evaluator = ClusteringEvaluator()
silhouette = evaluator.evaluate(predictions)


# In[75]:


print('Silhouette Score of the Clustering Result using 100 OHE Top Ports, without using PCA, is ', silhouette)


# In[76]:


centers = kmModel.clusterCenters()


# # We will later use this two dimensional arrays ``centers[i][j]`` to access the cluster center for each port (jth top port) for cluster (i) generated by clustering using the k-means model.

# In[77]:


print(centers)


# # Similar to Miniproject 2, record cluster index, cluster size, percentage of Mirai scanners, and cluster centers for each clusters formed.
# ## The value of cluster center for a OHE top port is the percentage of data/clusters in the cluster that scans the top port. For example, a cluster center `[0.094, 0.8, 0, ...]` indicates the following
# - 9.4% of the scanners in the cluster scan Top_Ports_list[0]: port 17132
# - 80% of the scanners in the cluster scan Top_Ports_list[1]: port 17130
# - No scanners in the cluster scan Top_Ports_list[2]: port 17140

# # Exercise 6 (10 points) Complete the code below for computing the percentage of Mirai scanners for each scanner, and record it together with cluster centers for each cluster (without PCA).

# In[78]:


import pandas as pd
import numpy as np
import math


# In[79]:


c1_centers = centers[0][0:99]


# In[80]:


print(c1_centers)


# In[82]:


# Define columns of the Pandas dataframe
column_list = ['cluster ID', 'size', 'mirai_ratio' ]
for feature in input_features:
    column_list.append(feature)
clusters_summary_df = pd.DataFrame( columns = column_list )
for i in range(0, total_clusters):
    cluster_i = predictions.where(col("prediction")==i)
    cluster_i.persist()
    cluster_i_size = cluster_i.count()
    cluster_i_mirai_count = cluster_i.where(col('mirai')).count()
    cluster_i_mirai_ratio = cluster_i_mirai_count/cluster_i_size
    if cluster_i_mirai_count > 0:
        print("Cluster ", i, "; Mirai Ratio:", cluster_i_mirai_ratio, "; Cluster Size: ", cluster_i_size)
    cluster_row = [i, cluster_i_size, cluster_i_mirai_ratio]
    for j in range(0, len(input_features)):
        cluster_row.append(centers[i][j] )
    clusters_summary_df.loc[i]= cluster_row
    cluster_i.unpersist()


# In[83]:


path4= "/storage/home/tkk5297/work/MiniProj3/cluster/Clusters_Mirai_Ratio_100OHE_k200.csv"
clusters_summary_df.to_csv(path4, header=True)


# In[84]:


predictions.unpersist()


# # Part C Using PCA for Dimension Reduction

# # We use PCA to reduce the input dimension from 100 to 30.

# In[85]:


pca_model = PCA(k=30, inputCol = "features", outputCol="pca_features")


# # The `pca_model` is a template for constructing a PCA model.
# ## After we apply `fit` to a PCA template, we obtain an actual mapping from the original feature space to the PCA space.

# In[86]:


p_model = pca_model.fit(data)


# In[87]:


p_data = p_model.transform(data)


# In[88]:


p_data.persist()


# ## Notice we change the `featuresCol` for k-means clustering to `"pca_features"` because we want to use its reduced dimension for clustering.

# In[89]:


total_clusters = 200
km2 = KMeans(featuresCol= "pca_features", predictionCol="pca_prediction").setK(total_clusters).setSeed(123)
km2.explainParams()


# In[90]:


data.unpersist()


# In[91]:


kmModel_p=km2.fit(p_data)


# In[92]:


kmModel_p


# In[93]:


p_predictions = kmModel_p.transform(p_data)


# In[94]:


p_predictions.persist()


# In[95]:


summary_p = kmModel_p.summary


# In[96]:


summary_p.clusterSizes


# # Notice that we need to specify `featuresCol` explicitly because the default is "features", but we are using "pca_features" as input features for Part C.

# In[97]:


evaluator = ClusteringEvaluator(predictionCol="pca_prediction", featuresCol="pca_features")
silhouette = evaluator.evaluate(p_predictions)


# In[98]:


print('Silhouette Score of the Clustering Result Using PCA-reduced dimension 30 is ', silhouette)


# In[99]:


top_k_ports


# # Compute the Cluster Centers from clustering on PCA (reduced) dimensions in the original dimensions (One Hot Encoded features, i.e., top ports)

# ## Record the cluster centers in the ``cluster_center_array`` where the row index refers to clusters, and the column index refers to OHE features (i.e., top ports).

# In[100]:


import numpy as np
# Initialize the cluster center array (for the original port dimensions) to zeros
cluster_center_array = np.zeros([200,100])


# ## Filter the p_prediction DataFrame on a specific OHE (top port) feature, which returns all scanners that scan the specific top port.
# ## Applying ``groupBy`` on``pca_prediction`` group the filtered scanners by the cluster they belong to (based on clustering on PCA dimensions).
# ## Applying ``count()`` to the DataFrame returned by ``GroupBy`` computes the total number of scanners (that scan the specified top port) in each cluster from PCA_kMeans_clustering.

# ## Below is an example for the OHE feature for the first top port.

# In[101]:


i=0
feature_name= "Port" + Top_Ports_list[i]
feature_i_count_by_clusters = p_predictions.where(col(feature_name)).groupBy("pca_prediction").count()


# In[102]:


fc_bc_rdd = feature_i_count_by_clusters.rdd


# In[103]:


fc_bc_rdd.take(2)


# ## The result above shows that 
# - 72 scanners in cluster 148 from PCA_kmeans_clustering scans the first top port.
# - 327 scanners in cluster 85 from PCA_kmeans_clustering scans the first top port.

# In[104]:


fc_bc_list =fc_bc_rdd.collect()


# In[105]:


print(fc_bc_list)


# # By iterating through ``fc_bc_list`` generated above, we can find the number of scanners that scan a given top port in each cluster generated by PCA_kmeans_clustering.

# In[106]:


# For the first top port, the number of scanners in each PCA-generated cluster that scan the port.
for row in fc_bc_list:
    print("PCA_kmeans Cluster Index ", row[0], ": contains ", row[1], " scanners that scan Port ", Top_Ports_list[0] )


# In[107]:


p_predictions.persist()
for i in range(0, top_k_ports):
    feature_i_name = "Port" + Top_Ports_list[i]
    feature_i_count_by_clusters_DF = p_predictions.where(col(feature_i_name)).groupBy(col("pca_prediction")).count()
    fic_bc_list = feature_i_count_by_clusters_DF.rdd.collect()
    # fic_bc_list is a list of (cluster_index, count of scanners that scan ith top port)
    # print("Count of Top Port ", i, ": ", feature_i_name, "by clusters")
    # print(" Cluster : ", fic_bc_list[i][0], "Count: ", fic_bc_list[i][1])
    for row in fic_bc_list:
        cluster_center_array[row[0]][i] = row[1]


# In[108]:


total_clusters = 200


# In[109]:


import pandas as pd


# # Exercise 7 (25 points)
# ## Complete the code below for computing cluster centers for each cluster using the ``cluster_center_array`` calculated above.

# In[110]:


# The number of total clusters (`total_clusters`) was specified earlier when we created k-means model template. 
# Define columns of the Pandas dataframe
column_list = ['cluster ID', 'size', 'mirai_ratio' ]
for feature in input_features:
    column_list.append(feature)
clusters_summary_df = pd.DataFrame( columns = column_list )
for i in range(0, total_clusters):
    cluster_i = p_predictions.where(col("pca_prediction") == i)
    cluster_i.persist()
    cluster_i_size = cluster_i.count()
    cluster_i_mirai_count = cluster_i.where(col('mirai')).count()
    cluster_i_mirai_ratio = cluster_i_mirai_count/cluster_i_size
    if cluster_i_mirai_count > 0:
        print("Cluster ", i, "; Mirai Ratio:", cluster_i_mirai_ratio, "; Cluster Size: ", cluster_i_size)
    cluster_row = [i, cluster_i_size, cluster_i_mirai_ratio]
    for j in range(0, len(input_features)):
        # compute the center for the original jth feature (i.e., jth top port)
        feature_j = "Port" + Top_Ports_list[j]
        count_i_j = cluster_center_array[i][j]
        # count_j = cluster_i.where(col(feature_j)).count()
        center_j = count_i_j / cluster_i_size
        cluster_row.append(center_j)
    clusters_summary_df.loc[i]= cluster_row
    cluster_i.unpersist()


# In[111]:


path5= "/storage/home/tkk5297/work/MiniProj3/cluster/Mirai_Ratio_100OHE_PCA30_k200.csv"
clusters_summary_df.to_csv(path5, header=True)


# In[112]:


clusters_summary_df


# # Exercise 8 (40 points)
# Modify the Jupyter Notebook for running in cluster mode using the big dataset (Day_2020_profile.csv). Make sure you change the output directory from `../local/..` to
# `../cluster/..` so that it does not destroy the result you obtained in local mode.
# Run the .py file the cluster mode to calculate cluster centers and Mirai percentage for each cluster with and without PCA.
# - Submit the .py file  (5 points)
# - Submit the the log file that contains the run time information for a successful execution in the cluster mode. (5 points)
# - Submit the output file that records the cluster summary in the cluster mode (without PCA) (10 points)
# - Submit the output file that records the cluster summary in the cluster mode (with PCA) (10 points)
# - Discuss the Silihouette score and Mirai ratio of clusters generated by k-means clustering with PCA and without PCA (in a separate word document) (10 points)

# In[113]:


ss.stop()


# In[ ]:




